config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { 
			:omniauth_callbacks => 'users/omniauth_callbacks'
	}, path: '', path_names: { 
		sign_in: 'signin', 
		sign_out: 'signout',
		sign_up: 'register'
	}

	resources :users do
	end

	resources :task_lists,    only: [:show, :create, :update] do
    resources :tasks,					only: [:create, :update, :destroy]
  end

	authenticated do
		root to: 'users#home', as: 'dashboard'
	end

	root to: 'static_pages#home'

  get 'help', to: 'static_pages#help'
	get 'about', to: 'static_pages#about'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :task_lists, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
				 :confirmable, :lockable,
				 :omniauthable, :omniauth_providers => [:google_oauth2]

	enum provider: [:google]

	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	def self.find_for_google_oauth2(auth, crurrent_user)
		where(auth.slice(:provider, :uid)).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name || user.email.split('@')[0]
			user.image = auth.info.image
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.skip_confirmation! if auth.info.verified
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # works with single deivse controller, User
  before_filter :configure_devise_params, if: :devise_controller?
    def configure_devise_params
      devise_parameter_sanitizer.for(:sign_up) << UsersController.extra_params
      devise_parameter_sanitizer.for(:account_update) << UsersController.extra_params
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

	def about
	end

  def help
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  def show
  end

  def create
  end

  def update
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_task_list, only: :create

  def index
  end

  def show
  end

  def create
    @task = @task_list.tasks.build(post_params)
    #@task.user_id = current_user.id
    if @task.save
      flash[:success] = "Task created!"
      redirect_to root_url
    else
      @tasks = []
      render 'users/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to root_url
  end

  private 
    def post_params
      params.require(:task).permit(:content)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

    def get_task_list
      @task_list = current_user.task_lists.find_by(id: params[:task_list_id])
      redirect_to root_url if @task_list.nil?
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
		Rails.logger.debug("#{request.env['omniauth.auth']}")

    if @user.persisted?
      flash[:notice] = "Successfully authenticated Google account"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
	before_action :authenticate_user!, only: [:index, :home, :following, :followers]

	def index
		@users = User.paginate(page: params[:page])	
	end

	def home
    if user_signed_in?
      @task_lists = current_user.task_lists
      if @task_lists.empty?
        current_user.task_lists.build(name: "Tasks")
        current_user.task_lists.build(name: "Archive")
        current_user.save
      end

      @task_list = @task_lists.first
      @tasks = @task_list.tasks
      @new_task = @tasks.build
    end
	end

	def show
    #@posts = @user.posts.paginate(page: params[:page])
	end

	# used in devise :sign_up and :update_account
	def self.extra_params
		:name
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

=begin
		def user_params
			params.require(:user).permit(:name, :email, :password, 
						:password_confirmation, :current_password)
		end
=end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">

  </div>
</footer>

app/views/layouts/_header.html.erb
<%# invoked with: render 'layouts/header' %>
<header>
  <div class="navbar">
    <div class="container">
      <%= link_to "Tasks", "#", id: "logo" %>
      <nav class="top-bar hide-for-small" data-topbar>
        <section class="top-bar-section">
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="has-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="carret"></b>
              </a>
              <ul class="dropdown">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: "delete", :class => 'navbar-link' %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Create Account", new_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
      </section>
      </nav>
      <nav class="top-bar show-for-small">
        <a class="left-off-canvas-toggle menu-icon">
          <span>Tasks</span>
        </a>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) + " | Tasks" : "Tasks"%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="error_message">
		<h2><%= pluralize(object.errors.count, "error") %></h2>	
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_task.html.erb
<% if task.id %>
<li id="<%= task.id %>">
  <span class="content"><%= task.content %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(task.created_at) %> ago.
  </span>
</li>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for [@task_list, @new_task] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "What to do?" %>
    <%= f.submit 'Add', class: "button" %>
  </div>
<% end %>

app/views/shared/_task_list.html.erb
<li id="<%= task_list.id %>">
  <span class="name">
    <%= link_to task_list.name, task_list %>
  </span>
  <span class="timestamp">
    Created <%= time_ago_in_words(task_list.created_at) %> ago.
  </span>
</li>

app/views/shared/_task_lists.html.erb
<% if @task_lists.any? %>
  <ol class="posts">
    <%= render partial: 'shared/task_list', collection: @task_lists %>
  </ol>
<% end %>

app/views/shared/_tasks.html.erb
<% if @tasks.any? %>
  <ol class="tasks">
    <%= render partial: 'shared/task', collection: @tasks %>
  </ol>
  <%# will_paginate @tasks %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "View profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p> This is the about page for this website that is cool.</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h2 class="tagline">Hello world</h2>

<div>
  <%= link_to "Sign up with Google", user_omniauth_authorize_path(:google_oauth2), class: "button" %>
</div>

app/views/tasks/_task.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user? post.user %>
    <%= link_to "delete", post, method: :delete,
                                data: { confirm: "Are you sure?" },
                                title: post.content %>
  <% end %>
</li>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
</li>

app/views/users/home.html.erb
<section>
  <%# render 'shared/stats' %>
</section>
<div class="feed">
  <h4>Task Lists</h4>
  <%= render 'shared/task_lists' %>
  <h4>Tasks</h4>
  <%= render 'shared/task_form' %>
  <%= render 'shared/tasks' %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<%= render user %>
	<% end %>
	<%# render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>

<%= render 'follow_form' if user_signed_in? %>
<%= render 'shared/stats' %>

<div>
  <% if @user.posts.any? %>
    <h3>Posts (<%= @user.posts.count %>)</h3>
    <ol class="posts">
      <%= render @posts %>
    </ol>
    <%= will_paginate @posts %>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <section>
    <h1><%= @user.name %></h1>
    <span><%= link_to "view my profile", @user %></span>
    <span><b>Posts:</b><%= @user.posts.count %></span>
  </section>
  <section>
    <%= render 'shared/stats' %>
    <div class="users">
      <% @users.each do |user| %>
        <%= link_to user.name, user %>
      <% end %>
    </div>
  </section>
  <div>
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%== render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>